-- Create members table
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    tier VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Create books table
CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    isbn VARCHAR(100) NOT NULL UNIQUE,
    author VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    total_copies INT NOT NULL DEFAULT 0,
    available_copies INT NOT NULL DEFAULT 0,
    replacement_cost DECIMAL(10, 2) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Create book_copies table
CREATE TABLE book_copies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    barcode VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Create loans table
CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
    book_copy_id BIGINT NOT NULL REFERENCES book_copies(id) ON DELETE RESTRICT,
    checkout_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    return_date TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(50) NOT NULL,
    idempotency_key VARCHAR(255) UNIQUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Create reservations table
CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    book_copy_id BIGINT REFERENCES book_copies(id) ON DELETE SET NULL,
    request_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL,
    collection_expiry_date TIMESTAMP WITHOUT TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Create fines table
CREATE TABLE fines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL REFERENCES loans(id) ON DELETE RESTRICT,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Create indexes for performance
CREATE INDEX idx_book_copies_book ON book_copies(book_id);
CREATE INDEX idx_loans_member ON loans(member_id);
CREATE INDEX idx_loans_copy ON loans(book_copy_id);
CREATE INDEX idx_reservations_member ON reservations(member_id);
CREATE INDEX idx_reservations_book ON reservations(book_id);
CREATE INDEX idx_fines_member ON fines(member_id);
CREATE INDEX idx_fines_loan ON fines(loan_id);

-- Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

-- Seed mock users
INSERT INTO users (id, email, password_hash, role)
VALUES
(1, 'john.reg@library.com', '$2b$12$R93OQDAOJ1wPA.tkVnlV7u/QcHWFDyXxhZCxCP3Ny2vgU.ZeK831e', 'ROLE_MEMBER'),
(2, 'alice.sup@library.com', '$2b$12$R93OQDAOJ1wPA.tkVnlV7u/QcHWFDyXxhZCxCP3Ny2vgU.ZeK831e', 'ROLE_MEMBER'),
(3, 'bob.reg@library.com', '$2b$12$R93OQDAOJ1wPA.tkVnlV7u/QcHWFDyXxhZCxCP3Ny2vgU.ZeK831e', 'ROLE_MEMBER'),
(4, 'diana.sup@library.com', '$2b$12$R93OQDAOJ1wPA.tkVnlV7u/QcHWFDyXxhZCxCP3Ny2vgU.ZeK831e', 'ROLE_MEMBER'),
(99, 'sarah.lib@library.com', '$2b$12$R93OQDAOJ1wPA.tkVnlV7u/QcHWFDyXxhZCxCP3Ny2vgU.ZeK831e', 'ROLE_LIBRARIAN'),
(100, 'mark.lib@library.com', '$2b$12$R93OQDAOJ1wPA.tkVnlV7u/QcHWFDyXxhZCxCP3Ny2vgU.ZeK831e', 'ROLE_LIBRARIAN');

-- Seed mock members
INSERT INTO members (id, name, email, tier, status, version, created_at)
VALUES
(1, 'John (Regular)', 'john.reg@library.com', 'REGULAR', 'ACTIVE', 0, NOW()),
(2, 'Alice (Supporting)', 'alice.sup@library.com', 'SUPPORTING', 'ACTIVE', 0, NOW()),
(3, 'Bob (Regular)', 'bob.reg@library.com', 'REGULAR', 'ACTIVE', 0, NOW()),
(4, 'Diana (Supporting)', 'diana.sup@library.com', 'SUPPORTING', 'ACTIVE', 0, NOW());

-- Seed mock books
INSERT INTO books (id, title, isbn, author, category, total_copies, available_copies, replacement_cost, version, created_at)
VALUES 
(1, 'The Hobbit', '978-0-261-10221-7', 'J.R.R. Tolkien', 'Fantasy', 3, 3, 15.00, 0, NOW()),
(2, 'To Kill a Mockingbird', '978-0-446-31078-9', 'Harper Lee', 'Fiction', 2, 2, 12.00, 0, NOW()),
(3, '1984', '978-0-451-52493-5', 'George Orwell', 'Dystopian', 1, 1, 10.00, 0, NOW());

-- Seed mock book copies
INSERT INTO book_copies (id, book_id, barcode, status, version, created_at)
VALUES
(1, 1, 'HOBBIT-001', 'AVAILABLE', 0, NOW()),
(2, 1, 'HOBBIT-002', 'AVAILABLE', 0, NOW()),
(3, 1, 'HOBBIT-003', 'AVAILABLE', 0, NOW()),
(4, 2, 'MOCKINGBIRD-001', 'AVAILABLE', 0, NOW()),
(5, 2, 'MOCKINGBIRD-002', 'AVAILABLE', 0, NOW()),
(6, 3, '1984-001', 'AVAILABLE', 0, NOW());

-- Synchronize sequences
SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id), 1)) FROM users;
SELECT setval(pg_get_serial_sequence('members', 'id'), coalesce(max(id), 1)) FROM members;
SELECT setval(pg_get_serial_sequence('books', 'id'), coalesce(max(id), 1)) FROM books;
SELECT setval(pg_get_serial_sequence('book_copies', 'id'), coalesce(max(id), 1)) FROM book_copies;
